# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    - name: Check test coverage and generate badges
      if: github.ref == 'refs/heads/main'
      uses: vladopajic/go-test-coverage@f94bcf0d6b9fa5fb8b783830b22648f6c17475e2 # v2.19.0
      with:
        config: ./.github/.testcoverage.yml
        git-branch: badges
        git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
    
    - name: Check test coverage
      if: github.ref != 'refs/heads/main'
      uses: vladopajic/go-test-coverage@f94bcf0d6b9fa5fb8b783830b22648f6c17475e2 # v2.19.0
      with:
        config: ./.github/.testcoverage.yml
